export const IS_SERVER_ALIVE = 'AS_IS_SERVER_ALIVE';
export const IS_SERVER_ALIVE_BEGIN = 'AS_IS_SERVER_ALIVE_BEGIN';
export const IS_SERVER_ALIVE_RECEIVED = 'AS_IS_SERVER_ALIVE_RECEIVED';
export const IS_SERVER_ALIVE_COMPLETED = 'AS_IS_SERVER_ALIVE_COMPLETED';
export const IS_SERVER_ALIVE_TIMEOUT = 'AS_IS_SERVER_ALIVE_TIMEOUT';
export const IS_SERVER_ALIVE_ERROR = 'AS_IS_SERVER_ALIVE_ERROR';
