export const IS_SERVER_ALIVE = 'AS_IS_SERVER_ALIVE';
export const IS_SERVER_ALIVE_BEGIN = 'AS_IS_SERVER_ALIVE_BEGIN';
export const IS_SERVER_ALIVE_RECEIVED = 'AS_IS_SERVER_ALIVE_RECEIVED';
export const IS_SERVER_ALIVE_COMPLETED = 'AS_IS_SERVER_ALIVE_COMPLETED';
export const IS_SERVER_ALIVE_TIMEOUT = 'AS_IS_SERVER_ALIVE_TIMEOUT';
export const IS_SERVER_ALIVE_ERROR = 'AS_IS_SERVER_ALIVE_ERROR';

export const GET_APARTMENT_STATUS = 'AS_GET_APARTMENT_STATUS';
export const GET_APARTMENT_STATUS_BEGIN = 'AS_GET_APARTMENT_STATUS_BEGIN';
export const GET_APARTMENT_STATUS_RECEIVED = 'AS_GET_APARTMENT_STATUS_RECEIVED';
export const GET_APARTMENT_STATUS_COMPLETED =
  'AS_GET_APARTMENT_STATUS_COMPLETED';
export const GET_APARTMENT_STATUS_TIMEOUT = 'AS_GET_APARTMENT_STATUS_TIMEOUT';
export const GET_APARTMENT_STATUS_ERROR = 'AS_GET_APARTMENT_STATUS_ERROR';
