export const IS_ALIVE_REQUEST = 'IS_ALIVE';
export const GET_ALL_CAMERAS_REQUEST = 'GET_ALL_CAMERAS';
export const GET_CAMERA_IMAGE_REQUEST = 'GET_CAMERA_IMAGE';
export const GET_SURVEILLANCE_STATUS = 'GET_SURVEILLANCE_STATUS';
