export const SEND_TEST_MESSAGE = 'S_SEND_TEST_MESSAGE';
export const GET_SURVEILLANCE_STATUS = 'S_GET_SURVEILLANCE_STATUS';
export const IS_SERVER_ALIVE = 'S_IS_SERVER_ALIVE';
export const GET_ALL_CAMERAS = 'S_GET_ALL_CAMERAS';
export const GET_CAMERA_IMAGE = 'S_GET_CAMERA_IMAGE';
